export { Dashboard } from "./dashboard/dashboard";
export { Help } from "./help/help";
export { Inventory } from "./inventory/inventory";
export { Login } from "./login/login";
export { Register } from "./register/register";
export { Reports } from "./Reports/reports";
export { SalesOrder } from "./salesorder/salesorder";
export { Settings } from "./settings/settings";
export { Supliers } from "./supliers/supliers";
